name: Get Android Version Name and Version Code 
description: Finds the version code and version name in your build.gradle file and publishes it as env vars.
author: gagandeep3458
inputs:
  path:
    required: false
    description: Path to your app's build.gradle
    default: app/build.gradle
  expose-version-code:
    required: true
    description: Expose version code
  expose-version-name:
    required: true
    description: Expose version name
runs:
  using: node16
  main: dist/index.js
